class SopExporter
  def self.call(sop, format: :markdown)
    new(sop).export(format)
  end

  def initialize(sop)
    @sop = sop
  end

  def export(format)
    case format
    when :markdown then to_markdown
    when :json     then sop_to_json
    when :pdf      then to_pdf
    else
      raise ArgumentError, "Unsupported format: #{format}"
    end
  end

  private

  def sop_to_json
    {
      id: @sop.id,
      title: @sop.title,
      description: @sop.description,
      status: @sop.status,
      tags: @sop.tags,
      steps: @sop.steps,
      confidence: @sop.confidence
    }.to_json
  end

  def to_markdown
    lines = []
    lines << "# #{@sop.title}"
    lines << ""
    lines << @sop.description.to_s
    lines << ""
    lines << "**Status:** #{@sop.status}  "
    lines << "**Tags:** #{Array(@sop.tags).join(', ')}  "
    lines << "**Confidence:** #{(@sop.confidence.to_f * 100).round}%"
    lines << ""
    lines << "## Steps"
    Array(@sop.steps).each_with_index do |step, idx|
      lines << ""
      lines << "### #{idx + 1}. #{step['title']}"
      lines << ""
      lines << step["description"].to_s
      if step["application"]
        lines << ""
        lines << "_Application: #{step['application']}_"
      end
      if (decision = step["decision"])
        lines << ""
        lines << "**Decision:** #{decision['question']}"
        Array(decision["branches"]).each do |branch|
          lines << "- #{branch['label']}"
        end
      end
    end
    lines.join("\n")
  end

  def to_pdf
    require "prawn"
    Prawn::Fonts::AFM.hide_m17n_warning = true if defined?(Prawn::Fonts::AFM)

    pdf_text =
      Prawn::Document.new(page_size: "LETTER", margin: [54, 54, 54, 54]) do |pdf|
        pdf.font_size 20
        pdf.text utf8_safe(@sop.title), style: :bold
        pdf.move_down 12

        pdf.font_size 10
        pdf.text utf8_safe(@sop.description.to_s), leading: 2

        pdf.move_down 14
        pdf.stroke_horizontal_rule
        pdf.move_down 14

        pdf.font_size 9
        pdf.fill_color "666666"
        meta_bits = [
          "Status: #{@sop.status}",
          "Confidence: #{(@sop.confidence.to_f * 100).round}%",
          Array(@sop.tags).presence&.join(", ")&.then { |t| "Tags: #{t}" },
        ].compact
        pdf.text utf8_safe(meta_bits.join(" · "))
        pdf.fill_color "000000"

        pdf.move_down 18
        pdf.font_size 14
        pdf.text "Steps", style: :bold
        pdf.move_down 10

        Array(@sop.steps).each_with_index do |step, idx|
          pdf.font_size 11
          pdf.text "#{idx + 1}. #{utf8_safe(step['title'])}", style: :bold
          pdf.move_down 4
          pdf.font_size 10
          pdf.text utf8_safe(step["description"].to_s), leading: 2

          if step["application"]
            pdf.move_down 4
            pdf.font_size 9
            pdf.fill_color "444444"
            pdf.text "Application: #{utf8_safe(step['application'])}", style: :italic
            pdf.fill_color "000000"
          end

          if (decision = step["decision"])
            pdf.move_down 8
            pdf.font_size 9
            pdf.fill_color "92400E"
            pdf.text "Decision · #{utf8_safe(decision['question'])}", style: :bold
            pdf.fill_color "333333"
            Array(decision["branches"]).each do |branch|
              pdf.text "- #{utf8_safe(branch['label'])}"
            end
            pdf.fill_color "000000"
          end

          pdf.font_size 10
          pdf.move_down 14
        end

        pdf.move_down 8
        pdf.stroke_horizontal_rule
        pdf.move_down 12
        pdf.font_size 8
        pdf.fill_color "888888"
        pdf.text "Generated by Vopro · Exported #{Time.zone.now.utc.strftime('%Y-%m-%d %H:%M UTC')}",
          align: :center
      end.render
  end

  def utf8_safe(str)
    s = str.to_s
    return "" if s.empty?

    s.encode("UTF-8", invalid: :replace, undef: :replace, replace: "?")
  end
end
